colorScheme = "Marvel"
enableSearch = false

[homepage]
layout = "background"
homepageImage = "img/background.jpeg"

[header]
layout = "fixed-fill-blur"

[footer]
showThemeAttribution = false
showScrollToTop = true
